#!/usr/bin/env bash
# configures a brand new Ubuntu machine
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo 'Hello World' | sudo tee /var/www/html/index.html
findit="\tlocation / {"
replace="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@^$findit@$replace@" /etc/nginx/sites-available/default
sudo service nginx restart
