#!/usr/bin/env bash
# ufw setup per task requirements
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 413/tcp
sudo ufw allow 80/tcp
sudo ufw enable
